services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: sentinel-honeypot
    user: '0:0'
    ports:
      - '2222:2222'
      - '2323:2323'
    volumes:
      - cowrie_var:/cowrie/var
      - ./infra/honeypot/cowrie.cfg:/cowrie/etc/cowrie.cfg:ro
    restart: unless-stopped
    networks:
      - sentinel-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: sentinel-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - sentinel-net
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: sentinel-kibana
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false # The critical fix
    networks:
      - sentinel-net
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: sentinel-filebeat
    user: '0:0'
    depends_on:
      - elasticsearch
    volumes:
      - ./infra/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - cowrie_var:/log-data:ro
    networks:
      - sentinel-net
    restart: unless-stopped

  sentinel_app:
    build: .
    container_name: sentinel-app
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - elasticsearch
    command: uvicorn sentinel.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - sentinel-net
    restart: unless-stopped

volumes:
  cowrie_var:
  elastic_data:

networks:
  sentinel-net:
