filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /log-data/log/cowrie/cowrie.json
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
