strict.perms: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    # The /log-data volume points to /cowrie/var inside the Cowrie container
    - /log-data/log/cowrie/cowrie.json
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_URL:http://elasticsearch:9200}"]
  pipeline: geoip
  username: "${ELASTICSEARCH_USERNAME:}"
  password: "${ELASTICSEARCH_PASSWORD:}"
